### ISSUE TITLE
upgrade bios and the hackintosh fucked up

### ISSUE THREAD

**Issue by kevinchain** [red-green/razer_blade_stealth_hackintosh#2]
hi  red_green
 i upgrade my bios ,it  fucked up! it stucked ++++
![微信图片_20191204132425](https://user-images.githubusercontent.com/3047123/70115107-a7d84f80-1699-11ea-9ad8-b00818547d14.jpg)
![微信图片_20191204132431](https://user-images.githubusercontent.com/3047123/70115115-adce3080-1699-11ea-97d0-d45c0d635187.jpg)

**Comment by alinach120602** [comment]
It's probably because all of the SSDTs are compiled for the OLD Bios and there might be incompatibilities nonetheless. But the first thing to try is to recompile the SSDTs

**Comment by kevinchain** [comment]
> It's probably because all of the SSDTs are compiled for the OLD Bios and there might be incompatibilities nonetheless. But the first thing to try is to recompile the SSDTs

what's your bios version?

**Comment by alinach120602** [comment]
Sorry for the Late reply, my BIOS Version currently is: 2.01 / 1.01 / 1.00.00.00 Built 12/11/2017 14:25:48

**Comment by kevinchain** [comment]
> Sorry for the Late reply, my BIOS Version currently is: 2.01 / 1.01 / 1.00.00.00 Built 12/11/2017 14:25:48

use this tools  backup your bios ,and shared with me  [,tks![] 
tools link
https://drive.google.com/file/d/1yu7yJLDBdb6yGQlzmTLHl3wSR2CTAZ72/view?usp=sharing

**Comment by kevinchain** [comment]
> Sorry for the Late reply, my BIOS Version currently is: 2.01 / 1.01 / 1.00.00.00 Built 12/11/2017 14:25:48

and i will downgrade my bios .

**Comment by alinach120602** [comment]
The Application won't open on Windows 10
I've even tried AFUWIN (nongui) but it doesn't support the Razer BIOS

**Comment by alinach120602** [comment]
I download the AFUWINGUI from the AMI Website and it worked here is my BIOS for my
Late 2017 Razer Blade Stealth 13Inch 8550U no dGPU with 3200X1800 Display

https://drive.google.com/file/d/1DeJe76EIK0KSlZuqNKwjZ_A0Y9TiBVK9/view?usp=sharing

**Comment by murillomuller** [comment]
Guys i have the same problem, it works dowgrade the BIOS?

**Comment by alinach120602** [comment]
It’s my original BIOS so it will work, just make sure that you have the Quad Core i7 8550U QHD+ Razer Blade Stealth Late 2017 / early 2018 with the 3200x1800 Display and it will be fine.
